# 开发环境配置

# 数据源配置
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/easyweb-security?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource

spring:
  datasource:
    dynamic:
      primary: db1
      datasource:
        db1:
          url: jdbc:mysql://rm-uf67v4mwd5m8732oi7o.mysql.rds.aliyuncs.com:3306/easyweb-security?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: 5V2m4jxi
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
        db2:
          url: jdbc:mysql://rr-uf6plxb9pk6306631mo.mysql.rds.aliyuncs.com:3306/dxair?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
          username: root
          password: 5V2m4jxi
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
  autoconfigure:
    exclude:  com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

# 日志配置
logging:
  level:
    com.egao: DEBUG
    com.baomidou.mybatisplus: DEBUG
